#ifndef _RECIPENAME_HPP_
#define _RECIPENAME_HPP_

#include <string>

enum RecipeName
{
	RECIPE_SOURCE_LIMESTONE_IMPURE,
	RECIPE_SOURCE_LIMESTONE_NORMAL,
	RECIPE_SOURCE_LIMESTONE_PURE,
	RECIPE_SOURCE_IRON_IMPURE,
	RECIPE_SOURCE_IRON_NORMAL,
	RECIPE_SOURCE_IRON_PURE,
	RECIPE_SOURCE_COPPER_IMPURE,
	RECIPE_SOURCE_COPPER_NORMAL,
	RECIPE_SOURCE_COPPER_PURE,
	RECIPE_SOURCE_CATERIUM_IMPURE,
	RECIPE_SOURCE_CATERIUM_NORMAL,
	RECIPE_SOURCE_CATERIUM_PURE,
	RECIPE_SOURCE_COAL_IMPURE,
	RECIPE_SOURCE_COAL_NORMAL,
	RECIPE_SOURCE_COAL_PURE,
	RECIPE_SOURCE_OIL_IMPURE,
	RECIPE_SOURCE_OIL_NORMAL,
	RECIPE_SOURCE_OIL_PURE,
	RECIPE_SOURCE_SULFUR_IMPURE,
	RECIPE_SOURCE_SULFUR_NORMAL,
	RECIPE_SOURCE_SULFUR_PURE,
	RECIPE_SOURCE_BAUXITE_IMPURE,
	RECIPE_SOURCE_BAUXITE_NORMAL,
	RECIPE_SOURCE_BAUXITE_PURE,
	RECIPE_SOURCE_QUARTZ_IMPURE,
	RECIPE_SOURCE_QUARTZ_NORMAL,
	RECIPE_SOURCE_QUARTZ_PURE,
	RECIPE_SOURCE_URANIUM_IMPURE,
	RECIPE_SOURCE_URANIUM_NORMAL,
	RECIPE_SOURCE_URANIUM_PURE,
	RECIPE_SOURCE_WATER,

	RECIPE_IRON_INGOT,
	RECIPE_COPPER_INGOT,
	RECIPE_CATERIUM_INGOT,
	RECIPE_PURE_ALUMINUM_INGOT,
	
	RECIPE_COPPER_ALLOY_INGOT,
	RECIPE_IRON_ALLOY_INGOT,
	RECIPE_STEEL_INGOT,
	RECIPE_SOLID_STEEL_INGOT,
	RECIPE_COMPACTED_STEEL_INGOT,
	RECIPE_ALUMINUM_INGOT,
	RECIPE_COKE_STEEL_INGOT,
	
	RECIPE_IRON_PLATE,
	RECIPE_IRON_ROD,
	RECIPE_SCREW,
	RECIPE_COPPER_SHEET,
	RECIPE_CASTED_SCREW,
	RECIPE_STEEL_BEAM,
	RECIPE_STEEL_PIPE,
	RECIPE_STEEL_ROD,
	RECIPE_STEEL_SCREW,
	RECIPE_WIRE,
	RECIPE_CABLE,
	RECIPE_QUICKWIRE,
	RECIPE_IRON_WIRE,
	RECIPE_CATERIUM_WIRE,
	RECIPE_CONCRETE,
	RECIPE_QUARTZ_CRYSTAL,
	RECIPE_SILICA,
	RECIPE_BIOMASS_WOOD,
	RECIPE_BIOMASS_LEAVES,
	RECIPE_BIOMASS_MYCELIA,
	RECIPE_SOLID_BIOFUEL,
	RECIPE_SPIKED_REBAR,
	RECIPE_COLOR_CARTRIDGE,
	RECIPE_BIOCOAL,
	RECIPE_CHARCOAL,
	RECIPE_EMPTY_CANISTER,
	RECIPE_STEEL_CANISTER,
	
	RECIPE_REINFORCED_IRON_PLATE,
	RECIPE_MODULAR_FRAME,
	RECIPE_STITCHED_IRON_PLATE,
	RECIPE_BOLTED_FRAME,
	RECIPE_BOLTED_IRON_PLATE,
	RECIPE_STEELED_FRAME,
	RECIPE_ENCASED_INDUSTRIAL_BEAM,
	RECIPE_ENCASED_INDUSTRIAL_PIPE,
	RECIPE_ALCLAD_ALUMINUM_SHEET,
	RECIPE_ADHERED_IRON_PLATE,
	RECIPE_STEEL_COATED_PLATE,
	RECIPE_COATED_IRON_PLATE,
	RECIPE_AI_LIMITER,
	RECIPE_FUSED_QUICKWIRE,
	RECIPE_FUSED_WIRE,
	RECIPE_CIRCUIT_BOARD,
	RECIPE_CATERIUM_CIRCUIT_BOARD,
	RECIPE_QUICKWIRE_CABLE,
	RECIPE_INSULATED_CABLE,
	RECIPE_SILICONE_CIRCUIT_BOARD,
	RECIPE_ELECTRODE_CIRCUIT_BOARD,
	RECIPE_ROTOR,
	RECIPE_COPPER_ROTOR,
	RECIPE_STEEL_ROTOR,
	RECIPE_STATOR,
	RECIPE_MOTOR,
	RECIPE_QUICKWIRE_STATOR,
	RECIPE_HEAT_SINK,
	RECIPE_HEAT_EXCHANGER,
	RECIPE_SMART_PLATING,
	RECIPE_VERSATILE_FRAMEWORK,
	RECIPE_AUTOMATED_WIRING,
	RECIPE_BLACK_POWDER,
	RECIPE_NOBELISK,
	RECIPE_FINE_BLACK_POWDER,
	RECIPE_FABRIC,
	RECIPE_CHEAP_SILICA,
	RECIPE_FINE_CONCRETE,
	RECIPE_COMPACTED_COAL,
	RECIPE_RUBBER_CONCRETE,
	RECIPE_CRYSTAL_COMPUTER,
	RECIPE_ELECTROMAGNETIC_CONTROL_ROD,
	RECIPE_ENCASED_URANIUM_CELL,
	RECIPE_ELECTROMAGNETIC_CONNECTION_ROD,
	RECIPE_COATED_IRON_CANISTER,
	
	RECIPE_IODINE_INFUSED_FILTER,
	RECIPE_RIFLE_CARTRIDGE,
	RECIPE_SEISMIC_NOBELISK,
	RECIPE_GAS_FILTER,
	RECIPE_BEACON,
	RECIPE_CRYSTAL_BEACON,
	RECIPE_HIGH_SPEED_CONNECTOR,
	RECIPE_SILICONE_HIGH_SPEED_CONNECTOR,
	RECIPE_BATTERY,
	RECIPE_SUPERCOMPUTER,
	RECIPE_CRYSTAL_OSCILLATOR,
	RECIPE_RADIO_CONTROL_UNIT,
	RECIPE_RADIO_CONTROL_SYSTEM,
	RECIPE_INSULATED_CRYSTAL_OSCILLATOR,
	RECIPE_COMPUTER,
	RECIPE_CATERIUM_COMPUTER,
	RECIPE_HEAVY_MODULAR_FRAME,
	RECIPE_HEAVY_FLEXIBLE_FRAME,
	RECIPE_HEAVY_ENCASED_FRAME,
	RECIPE_AUTOMATED_SPEED_WIRING,
	RECIPE_FLEXIBLE_FRAMEWORK,
	RECIPE_PLASTIC_SMART_PLATING,
	RECIPE_MODULAR_ENGINE,
	RECIPE_ADAPTIVE_CONTROL_UNIT,
	RECIPE_RIGOUR_MOTOR,
	RECIPE_TURBO_MOTOR,
	RECIPE_TURBO_RIGOUR_MOTOR,
	RECIPE_NUCLEAR_FUEL_ROD,
	RECIPE_NUCLEAR_FUEL_UNIT,
	RECIPE_INFUSED_URANIUM_CELL,
	
	RECIPE_STEAMED_COPPER_SHEET,
	RECIPE_PURE_CATERIUM_INGOT,
	RECIPE_PURE_IRON_INGOT,
	RECIPE_PURE_COPPER_INGOT,
	RECIPE_WET_CONCRETE,
	RECIPE_PURE_QUARTZ_CRYSTAL,
	RECIPE_ALUMINUM_SCRAP,
	RECIPE_ALUMINA_SOLUTION,
	RECIPE_ELECTRODE_ALUMINUM_SCRAP,
	RECIPE_URANIUM_PELLET,
	RECIPE_SULFURIC_ACID,
	RECIPE_PLASTIC,
	RECIPE_RUBBER,
	RECIPE_PETROLEUM_COKE,
	RECIPE_RESIDUAL_PLASTIC,
	RECIPE_RESIDUAL_RUBBER,
	RECIPE_RECYCLED_RUBBER,
	RECIPE_RECYCLED_PLASTIC,
	RECIPE_POLYMER_RESIN,
	RECIPE_FUEL,
	RECIPE_RESIDUAL_FUEL,
	RECIPE_TURBO_HEAVY_FUEL,
	RECIPE_TURBOFUEL,
	RECIPE_LIQUID_BIOFUEL,
	RECIPE_DILUTED_PACKAGED_FUEL,
	RECIPE_COATED_CABLE,
	RECIPE_HEAVY_OIL_RESIDUE,
	RECIPE_POLYESTER_FABRIC,

	RECIPE_PACKAGED_TURBOFUEL,
	RECIPE_PACKAGED_WATER,
	RECIPE_PACKAGED_OIL,
	RECIPE_PACKAGED_FUEL,
	RECIPE_PACKAGED_HEAVY_OIL_RESIDUE,
	RECIPE_PACKAGED_LIQUID_BIOFUEL,
	RECIPE_UNPACKAGE_TURBOFUEL,
	RECIPE_UNPACKAGE_FUEL,
	RECIPE_UNPACKAGE_LIQUID_BIOFUEL,
	RECIPE_UNPACKAGE_WATER,
	RECIPE_UNPACKAGE_OIL,
	RECIPE_UNPACKAGE_HEAVY_OIL_RESIDUE,


	RECIPE_POWER_COAL_GENERATOR_COAL,
	RECIPE_POWER_COAL_GENERATOR_COMPACTED_COAL,
	RECIPE_POWER_COAL_GENERATOR_PETROLEUM_COKE,
	RECIPE_POWER_FUEL_GENERATOR_FUEL,
	RECIPE_POWER_FUEL_GENERATOR_LIQUID_BIOFUEL,
	RECIPE_POWER_FUEL_GENERATOR_TURBOFUEL,
	RECIPE_POWER_NUCLEAR_POWER_PLANT,
	RECIPE_POWER_GEOTHERMAL_GENERATOR,
	
	RECIPE_AWESOME_SINK,

	RECIPE_SIZE
};

// %s%\t\(.*\),%\tcase \1: return "\1";%g
std::string recipeToString(RecipeName name)
{
	switch(name)
	{
		case RECIPE_SOURCE_LIMESTONE_IMPURE: return "RECIPE_SOURCE_LIMESTONE_IMPURE";
		case RECIPE_SOURCE_LIMESTONE_NORMAL: return "RECIPE_SOURCE_LIMESTONE_NORMAL";
		case RECIPE_SOURCE_LIMESTONE_PURE: return "RECIPE_SOURCE_LIMESTONE_PURE";
		case RECIPE_SOURCE_IRON_IMPURE: return "RECIPE_SOURCE_IRON_IMPURE";
		case RECIPE_SOURCE_IRON_NORMAL: return "RECIPE_SOURCE_IRON_NORMAL";
		case RECIPE_SOURCE_IRON_PURE: return "RECIPE_SOURCE_IRON_PURE";
		case RECIPE_SOURCE_COPPER_IMPURE: return "RECIPE_SOURCE_COPPER_IMPURE";
		case RECIPE_SOURCE_COPPER_NORMAL: return "RECIPE_SOURCE_COPPER_NORMAL";
		case RECIPE_SOURCE_COPPER_PURE: return "RECIPE_SOURCE_COPPER_PURE";
		case RECIPE_SOURCE_CATERIUM_IMPURE: return "RECIPE_SOURCE_CATERIUM_IMPURE";
		case RECIPE_SOURCE_CATERIUM_NORMAL: return "RECIPE_SOURCE_CATERIUM_NORMAL";
		case RECIPE_SOURCE_CATERIUM_PURE: return "RECIPE_SOURCE_CATERIUM_PURE";
		case RECIPE_SOURCE_COAL_IMPURE: return "RECIPE_SOURCE_COAL_IMPURE";
		case RECIPE_SOURCE_COAL_NORMAL: return "RECIPE_SOURCE_COAL_NORMAL";
		case RECIPE_SOURCE_COAL_PURE: return "RECIPE_SOURCE_COAL_PURE";
		case RECIPE_SOURCE_OIL_IMPURE: return "RECIPE_SOURCE_OIL_IMPURE";
		case RECIPE_SOURCE_OIL_NORMAL: return "RECIPE_SOURCE_OIL_NORMAL";
		case RECIPE_SOURCE_OIL_PURE: return "RECIPE_SOURCE_OIL_PURE";
		case RECIPE_SOURCE_SULFUR_IMPURE: return "RECIPE_SOURCE_SULFUR_IMPURE";
		case RECIPE_SOURCE_SULFUR_NORMAL: return "RECIPE_SOURCE_SULFUR_NORMAL";
		case RECIPE_SOURCE_SULFUR_PURE: return "RECIPE_SOURCE_SULFUR_PURE";
		case RECIPE_SOURCE_BAUXITE_IMPURE: return "RECIPE_SOURCE_BAUXITE_IMPURE";
		case RECIPE_SOURCE_BAUXITE_NORMAL: return "RECIPE_SOURCE_BAUXITE_NORMAL";
		case RECIPE_SOURCE_BAUXITE_PURE: return "RECIPE_SOURCE_BAUXITE_PURE";
		case RECIPE_SOURCE_QUARTZ_IMPURE: return "RECIPE_SOURCE_QUARTZ_IMPURE";
		case RECIPE_SOURCE_QUARTZ_NORMAL: return "RECIPE_SOURCE_QUARTZ_NORMAL";
		case RECIPE_SOURCE_QUARTZ_PURE: return "RECIPE_SOURCE_QUARTZ_PURE";
		case RECIPE_SOURCE_URANIUM_IMPURE: return "RECIPE_SOURCE_URANIUM_IMPURE";
		case RECIPE_SOURCE_URANIUM_NORMAL: return "RECIPE_SOURCE_URANIUM_NORMAL";
		case RECIPE_SOURCE_URANIUM_PURE: return "RECIPE_SOURCE_URANIUM_PURE";
		case RECIPE_SOURCE_WATER: return "RECIPE_SOURCE_WATER";

		case RECIPE_IRON_INGOT: return "RECIPE_IRON_INGOT";
		case RECIPE_COPPER_INGOT: return "RECIPE_COPPER_INGOT";
		case RECIPE_CATERIUM_INGOT: return "RECIPE_CATERIUM_INGOT";
		case RECIPE_PURE_ALUMINUM_INGOT: return "RECIPE_PURE_ALUMINUM_INGOT";
		
		case RECIPE_COPPER_ALLOY_INGOT: return "RECIPE_COPPER_ALLOY_INGOT";
		case RECIPE_IRON_ALLOY_INGOT: return "RECIPE_IRON_ALLOY_INGOT";
		case RECIPE_STEEL_INGOT: return "RECIPE_STEEL_INGOT";
		case RECIPE_SOLID_STEEL_INGOT: return "RECIPE_SOLID_STEEL_INGOT";
		case RECIPE_COMPACTED_STEEL_INGOT: return "RECIPE_COMPACTED_STEEL_INGOT";
		case RECIPE_ALUMINUM_INGOT: return "RECIPE_ALUMINUM_INGOT";
		case RECIPE_COKE_STEEL_INGOT: return "RECIPE_COKE_STEEL_INGOT";
		
		case RECIPE_IRON_PLATE: return "RECIPE_IRON_PLATE";
		case RECIPE_IRON_ROD: return "RECIPE_IRON_ROD";
		case RECIPE_SCREW: return "RECIPE_SCREW";
		case RECIPE_COPPER_SHEET: return "RECIPE_COPPER_SHEET";
		case RECIPE_CASTED_SCREW: return "RECIPE_CASTED_SCREW";
		case RECIPE_STEEL_BEAM: return "RECIPE_STEEL_BEAM";
		case RECIPE_STEEL_PIPE: return "RECIPE_STEEL_PIPE";
		case RECIPE_STEEL_ROD: return "RECIPE_STEEL_ROD";
		case RECIPE_STEEL_SCREW: return "RECIPE_STEEL_SCREW";
		case RECIPE_WIRE: return "RECIPE_WIRE";
		case RECIPE_CABLE: return "RECIPE_CABLE";
		case RECIPE_QUICKWIRE: return "RECIPE_QUICKWIRE";
		case RECIPE_IRON_WIRE: return "RECIPE_IRON_WIRE";
		case RECIPE_CATERIUM_WIRE: return "RECIPE_CATERIUM_WIRE";
		case RECIPE_CONCRETE: return "RECIPE_CONCRETE";
		case RECIPE_QUARTZ_CRYSTAL: return "RECIPE_QUARTZ_CRYSTAL";
		case RECIPE_SILICA: return "RECIPE_SILICA";
		case RECIPE_BIOMASS_WOOD: return "RECIPE_BIOMASS_WOOD";
		case RECIPE_BIOMASS_LEAVES: return "RECIPE_BIOMASS_LEAVES";
		case RECIPE_BIOMASS_MYCELIA: return "RECIPE_BIOMASS_MYCELIA";
		case RECIPE_SOLID_BIOFUEL: return "RECIPE_SOLID_BIOFUEL";
		case RECIPE_SPIKED_REBAR: return "RECIPE_SPIKED_REBAR";
		case RECIPE_COLOR_CARTRIDGE: return "RECIPE_COLOR_CARTRIDGE";
		case RECIPE_BIOCOAL: return "RECIPE_BIOCOAL";
		case RECIPE_CHARCOAL: return "RECIPE_CHARCOAL";
		case RECIPE_EMPTY_CANISTER: return "RECIPE_EMPTY_CANISTER";
		case RECIPE_STEEL_CANISTER: return "RECIPE_STEEL_CANISTER";
		
		case RECIPE_REINFORCED_IRON_PLATE: return "RECIPE_REINFORCED_IRON_PLATE";
		case RECIPE_MODULAR_FRAME: return "RECIPE_MODULAR_FRAME";
		case RECIPE_STITCHED_IRON_PLATE: return "RECIPE_STITCHED_IRON_PLATE";
		case RECIPE_BOLTED_FRAME: return "RECIPE_BOLTED_FRAME";
		case RECIPE_BOLTED_IRON_PLATE: return "RECIPE_BOLTED_IRON_PLATE";
		case RECIPE_STEELED_FRAME: return "RECIPE_STEELED_FRAME";
		case RECIPE_ENCASED_INDUSTRIAL_BEAM: return "RECIPE_ENCASED_INDUSTRIAL_BEAM";
		case RECIPE_ENCASED_INDUSTRIAL_PIPE: return "RECIPE_ENCASED_INDUSTRIAL_PIPE";
		case RECIPE_ALCLAD_ALUMINUM_SHEET: return "RECIPE_ALCLAD_ALUMINUM_SHEET";
		case RECIPE_ADHERED_IRON_PLATE: return "RECIPE_ADHERED_IRON_PLATE";
		case RECIPE_STEEL_COATED_PLATE: return "RECIPE_STEEL_COATED_PLATE";
		case RECIPE_COATED_IRON_PLATE: return "RECIPE_COATED_IRON_PLATE";
		case RECIPE_AI_LIMITER: return "RECIPE_AI_LIMITER";
		case RECIPE_FUSED_QUICKWIRE: return "RECIPE_FUSED_QUICKWIRE";
		case RECIPE_FUSED_WIRE: return "RECIPE_FUSED_WIRE";
		case RECIPE_CIRCUIT_BOARD: return "RECIPE_CIRCUIT_BOARD";
		case RECIPE_CATERIUM_CIRCUIT_BOARD: return "RECIPE_CATERIUM_CIRCUIT_BOARD";
		case RECIPE_QUICKWIRE_CABLE: return "RECIPE_QUICKWIRE_CABLE";
		case RECIPE_INSULATED_CABLE: return "RECIPE_INSULATED_CABLE";
		case RECIPE_SILICONE_CIRCUIT_BOARD: return "RECIPE_SILICONE_CIRCUIT_BOARD";
		case RECIPE_ELECTRODE_CIRCUIT_BOARD: return "RECIPE_ELECTRODE_CIRCUIT_BOARD";
		case RECIPE_ROTOR: return "RECIPE_ROTOR";
		case RECIPE_COPPER_ROTOR: return "RECIPE_COPPER_ROTOR";
		case RECIPE_STEEL_ROTOR: return "RECIPE_STEEL_ROTOR";
		case RECIPE_STATOR: return "RECIPE_STATOR";
		case RECIPE_MOTOR: return "RECIPE_MOTOR";
		case RECIPE_QUICKWIRE_STATOR: return "RECIPE_QUICKWIRE_STATOR";
		case RECIPE_HEAT_SINK: return "RECIPE_HEAT_SINK";
		case RECIPE_HEAT_EXCHANGER: return "RECIPE_HEAT_EXCHANGER";
		case RECIPE_SMART_PLATING: return "RECIPE_SMART_PLATING";
		case RECIPE_VERSATILE_FRAMEWORK: return "RECIPE_VERSATILE_FRAMEWORK";
		case RECIPE_AUTOMATED_WIRING: return "RECIPE_AUTOMATED_WIRING";
		case RECIPE_BLACK_POWDER: return "RECIPE_BLACK_POWDER";
		case RECIPE_NOBELISK: return "RECIPE_NOBELISK";
		case RECIPE_FINE_BLACK_POWDER: return "RECIPE_FINE_BLACK_POWDER";
		case RECIPE_FABRIC: return "RECIPE_FABRIC";
		case RECIPE_CHEAP_SILICA: return "RECIPE_CHEAP_SILICA";
		case RECIPE_FINE_CONCRETE: return "RECIPE_FINE_CONCRETE";
		case RECIPE_COMPACTED_COAL: return "RECIPE_COMPACTED_COAL";
		case RECIPE_RUBBER_CONCRETE: return "RECIPE_RUBBER_CONCRETE";
		case RECIPE_CRYSTAL_COMPUTER: return "RECIPE_CRYSTAL_COMPUTER";
		case RECIPE_ELECTROMAGNETIC_CONTROL_ROD: return "RECIPE_ELECTROMAGNETIC_CONTROL_ROD";
		case RECIPE_ENCASED_URANIUM_CELL: return "RECIPE_ENCASED_URANIUM_CELL";
		case RECIPE_ELECTROMAGNETIC_CONNECTION_ROD: return "RECIPE_ELECTROMAGNETIC_CONNECTION_ROD";
		case RECIPE_COATED_IRON_CANISTER: return "RECIPE_COATED_IRON_CANISTER";
		
		case RECIPE_IODINE_INFUSED_FILTER: return "RECIPE_IODINE_INFUSED_FILTER";
		case RECIPE_RIFLE_CARTRIDGE: return "RECIPE_RIFLE_CARTRIDGE";
		case RECIPE_SEISMIC_NOBELISK: return "RECIPE_SEISMIC_NOBELISK";
		case RECIPE_GAS_FILTER: return "RECIPE_GAS_FILTER";
		case RECIPE_BEACON: return "RECIPE_BEACON";
		case RECIPE_CRYSTAL_BEACON: return "RECIPE_CRYSTAL_BEACON";
		case RECIPE_HIGH_SPEED_CONNECTOR: return "RECIPE_HIGH_SPEED_CONNECTOR";
		case RECIPE_SILICONE_HIGH_SPEED_CONNECTOR: return "RECIPE_SILICONE_HIGH_SPEED_CONNECTOR";
		case RECIPE_BATTERY: return "RECIPE_BATTERY";
		case RECIPE_SUPERCOMPUTER: return "RECIPE_SUPERCOMPUTER";
		case RECIPE_CRYSTAL_OSCILLATOR: return "RECIPE_CRYSTAL_OSCILLATOR";
		case RECIPE_RADIO_CONTROL_UNIT: return "RECIPE_RADIO_CONTROL_UNIT";
		case RECIPE_RADIO_CONTROL_SYSTEM: return "RECIPE_RADIO_CONTROL_SYSTEM";
		case RECIPE_INSULATED_CRYSTAL_OSCILLATOR: return "RECIPE_INSULATED_CRYSTAL_OSCILLATOR";
		case RECIPE_COMPUTER: return "RECIPE_COMPUTER";
		case RECIPE_CATERIUM_COMPUTER: return "RECIPE_CATERIUM_COMPUTER";
		case RECIPE_HEAVY_MODULAR_FRAME: return "RECIPE_HEAVY_MODULAR_FRAME";
		case RECIPE_HEAVY_FLEXIBLE_FRAME: return "RECIPE_HEAVY_FLEXIBLE_FRAME";
		case RECIPE_HEAVY_ENCASED_FRAME: return "RECIPE_HEAVY_ENCASED_FRAME";
		case RECIPE_AUTOMATED_SPEED_WIRING: return "RECIPE_AUTOMATED_SPEED_WIRING";
		case RECIPE_FLEXIBLE_FRAMEWORK: return "RECIPE_FLEXIBLE_FRAMEWORK";
		case RECIPE_PLASTIC_SMART_PLATING: return "RECIPE_PLASTIC_SMART_PLATING";
		case RECIPE_MODULAR_ENGINE: return "RECIPE_MODULAR_ENGINE";
		case RECIPE_ADAPTIVE_CONTROL_UNIT: return "RECIPE_ADAPTIVE_CONTROL_UNIT";
		case RECIPE_RIGOUR_MOTOR: return "RECIPE_RIGOUR_MOTOR";
		case RECIPE_TURBO_MOTOR: return "RECIPE_TURBO_MOTOR";
		case RECIPE_TURBO_RIGOUR_MOTOR: return "RECIPE_TURBO_RIGOUR_MOTOR";
		case RECIPE_NUCLEAR_FUEL_ROD: return "RECIPE_NUCLEAR_FUEL_ROD";
		case RECIPE_NUCLEAR_FUEL_UNIT: return "RECIPE_NUCLEAR_FUEL_UNIT";
		case RECIPE_INFUSED_URANIUM_CELL: return "RECIPE_INFUSED_URANIUM_CELL";
		
		case RECIPE_STEAMED_COPPER_SHEET: return "RECIPE_STEAMED_COPPER_SHEET";
		case RECIPE_PURE_CATERIUM_INGOT: return "RECIPE_PURE_CATERIUM_INGOT";
		case RECIPE_PURE_IRON_INGOT: return "RECIPE_PURE_IRON_INGOT";
		case RECIPE_PURE_COPPER_INGOT: return "RECIPE_PURE_COPPER_INGOT";
		case RECIPE_WET_CONCRETE: return "RECIPE_WET_CONCRETE";
		case RECIPE_PURE_QUARTZ_CRYSTAL: return "RECIPE_PURE_QUARTZ_CRYSTAL";
		case RECIPE_ALUMINUM_SCRAP: return "RECIPE_ALUMINUM_SCRAP";
		case RECIPE_ALUMINA_SOLUTION: return "RECIPE_ALUMINA_SOLUTION";
		case RECIPE_ELECTRODE_ALUMINUM_SCRAP: return "RECIPE_ELECTRODE_ALUMINUM_SCRAP";
		case RECIPE_URANIUM_PELLET: return "RECIPE_URANIUM_PELLET";
		case RECIPE_SULFURIC_ACID: return "RECIPE_SULFURIC_ACID";
		case RECIPE_PLASTIC: return "RECIPE_PLASTIC";
		case RECIPE_RUBBER: return "RECIPE_RUBBER";
		case RECIPE_PETROLEUM_COKE: return "RECIPE_PETROLEUM_COKE";
		case RECIPE_RESIDUAL_PLASTIC: return "RECIPE_RESIDUAL_PLASTIC";
		case RECIPE_RESIDUAL_RUBBER: return "RECIPE_RESIDUAL_RUBBER";
		case RECIPE_RECYCLED_RUBBER: return "RECIPE_RECYCLED_RUBBER";
		case RECIPE_RECYCLED_PLASTIC: return "RECIPE_RECYCLED_PLASTIC";
		case RECIPE_POLYMER_RESIN: return "RECIPE_POLYMER_RESIN";
		case RECIPE_FUEL: return "RECIPE_FUEL";
		case RECIPE_RESIDUAL_FUEL: return "RECIPE_RESIDUAL_FUEL";
		case RECIPE_TURBO_HEAVY_FUEL: return "RECIPE_TURBO_HEAVY_FUEL";
		case RECIPE_TURBOFUEL: return "RECIPE_TURBOFUEL";
		case RECIPE_LIQUID_BIOFUEL: return "RECIPE_LIQUID_BIOFUEL";
		case RECIPE_DILUTED_PACKAGED_FUEL: return "RECIPE_DILUTED_PACKAGED_FUEL";
		case RECIPE_COATED_CABLE: return "RECIPE_COATED_CABLE";
		case RECIPE_HEAVY_OIL_RESIDUE: return "RECIPE_HEAVY_OIL_RESIDUE";
		case RECIPE_POLYESTER_FABRIC: return "RECIPE_POLYESTER_FABRIC";

		case RECIPE_PACKAGED_TURBOFUEL: return "RECIPE_PACKAGED_TURBOFUEL";
		case RECIPE_PACKAGED_WATER: return "RECIPE_PACKAGED_WATER";
		case RECIPE_PACKAGED_OIL: return "RECIPE_PACKAGED_OIL";
		case RECIPE_PACKAGED_FUEL: return "RECIPE_PACKAGED_FUEL";
		case RECIPE_PACKAGED_HEAVY_OIL_RESIDUE: return "RECIPE_PACKAGED_HEAVY_OIL_RESIDUE";
		case RECIPE_PACKAGED_LIQUID_BIOFUEL: return "RECIPE_PACKAGED_LIQUID_BIOFUEL";
		case RECIPE_UNPACKAGE_TURBOFUEL: return "RECIPE_UNPACKAGE_TURBOFUEL";
		case RECIPE_UNPACKAGE_FUEL: return "RECIPE_UNPACKAGE_FUEL";
		case RECIPE_UNPACKAGE_LIQUID_BIOFUEL: return "RECIPE_UNPACKAGE_LIQUID_BIOFUEL";
		case RECIPE_UNPACKAGE_WATER: return "RECIPE_UNPACKAGE_WATER";
		case RECIPE_UNPACKAGE_OIL: return "RECIPE_UNPACKAGE_OIL";
		case RECIPE_UNPACKAGE_HEAVY_OIL_RESIDUE: return "RECIPE_UNPACKAGE_HEAVY_OIL_RESIDUE";

		case RECIPE_POWER_COAL_GENERATOR_COAL: return "RECIPE_POWER_COAL_GENERATOR_COAL";
		case RECIPE_POWER_COAL_GENERATOR_COMPACTED_COAL: return "RECIPE_POWER_COAL_GENERATOR_COMPACTED_COAL";
		case RECIPE_POWER_COAL_GENERATOR_PETROLEUM_COKE: return "RECIPE_POWER_COAL_GENERATOR_PETROLEUM_COKE";
		case RECIPE_POWER_FUEL_GENERATOR_FUEL: return "RECIPE_POWER_FUEL_GENERATOR_FUEL";
		case RECIPE_POWER_FUEL_GENERATOR_LIQUID_BIOFUEL: return "RECIPE_POWER_FUEL_GENERATOR_LIQUID_BIOFUEL";
		case RECIPE_POWER_FUEL_GENERATOR_TURBOFUEL: return "RECIPE_POWER_FUEL_GENERATOR_TURBOFUEL";
		case RECIPE_POWER_NUCLEAR_POWER_PLANT: return "RECIPE_POWER_NUCLEAR_POWER_PLANT";
		case RECIPE_POWER_GEOTHERMAL_GENERATOR: return "RECIPE_POWER_GEOTHERMAL_GENERATOR";
		
		case RECIPE_AWESOME_SINK: return "RECIPE_AWESOME_SINK";

		default: return "RECIPE_UNKNOWN_ERROR";
	}
}

std::string recipeToString(size_t name) {return recipeToString(RecipeName(name));}

#endif //_RECIPENAME_HPP_